version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: kod-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_STRAPI_URL=http://89.111.152.178/api
      - NODE_OPTIONS=--openssl-legacy-provider
    restart: unless-stopped
    networks:
      - kod-network
    depends_on:
      - strapi

  strapi:
    build:
      context: ./kod-site-strapi
      dockerfile: Dockerfile
    container_name: kod-strapi
    ports:
      - "1337:1337"
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi_password
      - NODE_ENV=production
    volumes:
      - ./kod-site-strapi:/app
      - strapi-uploads:/app/public/uploads
    restart: unless-stopped
    networks:
      - kod-network
    depends_on:
      - postgres

  postgres:
    image: postgres:14-bullseye
    container_name: kod-postgres
    environment:
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=strapi_password
      - POSTGRES_DB=strapi
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - kod-network

networks:
  kod-network:
    driver: bridge

volumes:
  postgres-data:
  strapi-uploads: